<?php
/*
self::$app->ctrl_table[url规则]="[路径:]控制器:路由";
*/
self::$app->ctrl_table['index.html']="\\cms\\controller\\webCtrl";
self::$app->ctrl_table['index.php']="\\cms\\controller\\webCtrl";
self::$app->ctrl_table['Main']="\\cms\\controller\\mainCtrl";
#self::$app->ctrl_table['/([A-Za-z]+)_list_(\d+)\.html$/']="\\ctrl\\Web:channel/$1/$2";
#self::$app->ctrl_table['/([A-Za-z]+)_view_(\d+)\.html$/']="\\ctrl\\Web:view/$1/$2";